### PR TITLE
bug: fixes for github and resource providers

### PR DESCRIPTION
**Pull request by jaredfholgate**
## Overview/Summary

A few bugs have been picked up since the plan and apply perms were split:

- The registering of resource providers on a brand new sub is not possible with the plan permissions
- The GitHub PR comment does not work for very large plans
- An error has been reported for another permission:

```
403 Code="AuthorizationFailed" Message="The client '83a5fcf5-b664-4278-84b3-d6c5a1ff608a' with object id '83a5fcf5-b664-4278-84b3-d6c5a1ff608a' does not have authorization to perform action 'Microsoft.Resources/deployments/exportTemplate/action' over scope '/subscriptions/6f734e46-d97b-495f-9be8-f600638f3808' or the scope is invalid
```

This permissions issue is related to the telemetry settings for the CAF module. Given this is only for internal use, the solution is to disable the telemetry.

## This PR fixes/adds/changes/removes

1. #33

### Breaking Changes

1. None

## Testing Evidence

The E2E tests will be run.

I also ran a manual test of deploying the basic template from GitHub and then running another plan / apply. This was successful, where it failed prior to these fixes.

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/alz-terraform-accelerator/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/alz-terraform-accelerator/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/alz-terraform-accelerator/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by jaredfholgate** [comment]
@matt-FFFFFF and @luke-taylor This PR is still a work in progress as waiting for feedback from @stalejohnsen on an error he is seeing and trying to replicate it myself. However, the resource providers registration is a genuine issue that I missed in my original testing as wasn't using vanilla subscriptions that didn't already have the providers registered. I have added the capability to register the resource providers if they are not already registered. This does not slow it down significantly as the AzAPI resource seems to be fire and forget.

Just adding you as reviewers while in draft in case you spot anything before I submit for merge review.

**Comment by jaredfholgate** [comment]
> @matt-FFFFFF and @luke-taylor This PR is still a work in progress as waiting for feedback from @stalejohnsen on an error he is seeing and trying to replicate it myself. However, the resource providers registration is a genuine issue that I missed in my original testing as wasn't using vanilla subscriptions that didn't already have the providers registered. I have added the capability to register the resource providers if they are not already registered. This does not slow it down significantly as the AzAPI resource seems to be fire and forget.
> 
> Just adding you as reviewers while in draft in case you spot anything before I submit for merge review.

I managed to re-create the permissions issue. It was related to the use of ARM deployments for the module telemetry. I have disabled the telemetry to avoid having to provide those permissions to the plan service principal. If the telemetry is important, we can look to create a custom role as part of the bootstrap at a later date.

**Comment by matt-FFFFFF** [comment]
Telemetry will be changing to a provider based approach so will not be an issue going forward

**Comment by jaredfholgate** [comment]
FYI, I am aware that the testing is not sufficient to capture issues like this. I have an issue that is designed to tackle this when time allows.

**Comment by jaredfholgate** [comment]
@matt-FFFFFF and @luke-taylor I am going to override the review and merge this, since it fixes an issue that could cause it to be unusable for anyone trying it. I have performed as much testing as I can to validate and am comfortable with the changes.

**Pull request merged**
