### PR TITLE
feature: governed pipelines

### PR DESCRIPTION
**Pull request by jaredfholgate**
## Overview/Summary

The PR implements governed templates for plan and apply stages to lock down what can be done with the identities.

Azure DevOps and GitHub have different implementations:

- GitHub: WIF subject is used to specify the template.
- Azure DevOps: Service Connection is used to specify the template.

## This PR fixes/adds/changes/removes

1. #26 

### Breaking Changes

1. This will introduce new parameters and deployment artefacts, but will not fundamentally break anything

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/alz-terraform-accelerator/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/alz-terraform-accelerator/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/alz-terraform-accelerator/tree/main)
- [x] Performed testing and provided evidence.
- [x] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by jaredfholgate** [comment]
@matt-FFFFFF and @luke-taylor I appreciate there are a lot of changes in this PR. Happy to run through a demo with you to explain what has changed.

**Comment by matt-FFFFFF** [comment]
> @matt-FFFFFF and @luke-taylor I appreciate there are a lot of changes in this PR. Happy to run through a demo with you to explain what has changed.

Yes please that would be useful

**Comment by jaredfholgate** [comment]
@matt-FFFFFF  and @luke-taylor Added the concurrency fix for GitHub as discussed. I think that Azure DevOps may suffer from the same issue if someone runs CI and CD at the same time, but can think of a resolution for that at the moment due to it being on the Service Connection or Environment as opposed to somewhere I can make it consistent.

**Comment by luke-taylor** [comment]
Looks good, only thing (slightly pedantic so no worries if too difficult). I wouldn't  "." some folders here. I think templates/.ci_cd can be just ci_cd because that folder will never be in the target repo(s), whereas templates/.ci_cd/.github/workflows and templates/.ci_cd/.azuredevops will be so it makes sense there. Secondly, maybe the templates/.templates folder could be named something like pipeline_templates or similar.

**Comment by jaredfholgate** [comment]
> Looks good, only thing (slightly pedantic so no worries if too difficult). I wouldn't "." some folders here. I think templates/.ci_cd can be just ci_cd because that folder will never be in the target repo(s), whereas templates/.ci_cd/.github/workflows and templates/.ci_cd/.azuredevops will be so it makes sense there. Secondly, maybe the templates/.templates folder could be named something like pipeline_templates or similar.

I think I did this more for ordering than anything else and is now redundant since we can explicitly set the target folder / file names. I think I will move the azure devops templates to root and remove the dots as suggested. Incoming...

**Review by luke-taylor — APPROVED** [review]

**Pull request merged**
